use crate::modules::*;

#[derive(Debug, PartialEq)]
pub enum Node {
    EmptyNode,
    Namespace(Box<NamespaceNode>),
    Prefix(Box<PrefixNode>),
    Organization(Box<OrganizationNode>),
    Contact(Box<ContactNode>),
    Description(Box<DescriptionNode>),
    Reference(Box<ReferenceNode>),
    ValueNode(Box<ValueNode>),
    EnumNode(Box<EnumNode>),
    EnumerationNode(Box<EnumerationNode>),
    Revision(Box<RevisionNode>),
    Typedef(Box<TypedefNode>),
    Default(Box<DefaultNode>),
    YangVersion(Box<YangVersionNode>),
    Import(Box<ImportNode>),
    Include(Box<IncludeNode>),
    RevisionDate(Box<RevisionDateNode>),
    Identity(Box<IdentityNode>),
    Feature(Box<FeatureNode>),
    Container(Box<ContainerNode>),
    List(Box<ListNode>),
    Key(Box<KeyNode>),
    Leaf(Box<LeafNode>),
    LeafList(Box<LeafListNode>),
    Base(Box<BaseNode>),
    Type(Box<TypeNode>),
    Mandatory(Box<MandatoryNode>),
    IfFeature(Box<IfFeatureNode>),
    Config(Box<ConfigNode>),
    Units(Box<UnitsNode>),
    Status(Box<StatusNode>),
    RangeInt(Box<Vec<RangeInt>>),
    RangeUint(Box<Vec<RangeUint>>),
}
